### ISSUE TITLE
Bcl2fastq breaks when indexes are missing in the samplesheet

### ISSUE THREAD

**Issue by brainstorm** [arteria-project/arteria-bcl2fastq#11]
The bcl2fastq mask code breaks with the gold flowcell:

https://bitbucket.org/brainstorm/gold_flowcell

Since it's trying to get the index from the samplesheet:

```
1,PhiX,PhiX,PhiX,,,,Test,PhiX
2,PhiX,PhiX,PhiX,,,,Test,PhiX
3,NA12878_100pM,NA12878_100pM,NA12878_100pM,,A016,CCGTCC,Test,NA12878_100pM
4,NA12878_200pM,NA12878_200pM,NA12878_200pM,,A016,CCGTCC,Test,NA12878_200pM
```

**Comment by johandahlberg** [comment]
@brainstorm: If you want to try this out now - it should work (at least it did for me). You can see an example of the curl command in the references PR.
