### ISSUE TITLE
prod requirements pandas==0.14 generates error

### ISSUE THREAD

**Issue by dlisn** [arteria-project/arteria-bcl2fastq#28]
Running the install instructions on https://github.com/arteria-project/arteria-packs results in a python incompatibility error (python 3.5> required) for pandas 0.14.1 when pip is run on arteria-bcl2fastq/requirements/prod by the docker build. Changing 0.14.1 to 024.0  seems to resolve this.

**Comment by johandahlberg** [comment]
Thank you for reporting this!
